name: Build and Deploy to AKS

on:
  push:
    branches:
      - aksdeploy

env:
  ACR_NAME: ecommerceacrprod
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  RESOURCE_GROUP: ecommerce-aks-rg
  AKS_CLUSTER: ecommerce-aks
  NAMESPACE: ecommerce
  IMAGE_TAG: ${{ github.sha }}

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to ACR
      run: |
        az acr login --name $ACR_NAME

    # ==========================
    # BUILD BACKEND
    # ==========================
    - name: Build Backend Image
      run: |
        docker build \
          -t $ACR_LOGIN_SERVER/ecommerce-backend:$IMAGE_TAG \
          "02-backend/spring-boot rest api"

    - name: Push Backend Image
      run: |
        docker push \
          $ACR_LOGIN_SERVER/ecommerce-backend:$IMAGE_TAG

    # ==========================
    # BUILD FRONTEND
    # ==========================
    - name: Build Frontend Image
      run: |
        docker build \
          -t $ACR_LOGIN_SERVER/ecommerce-frontend:$IMAGE_TAG \
          "03-frontend/angular-ecommerce"

    - name: Push Frontend Image
      run: |
        docker push \
          $ACR_LOGIN_SERVER/ecommerce-frontend:$IMAGE_TAG

    # ==========================
    # CONNECT TO AKS
    # ==========================
    - name: Get AKS Credentials
      run: |
        az aks get-credentials \
          --resource-group $RESOURCE_GROUP \
          --name $AKS_CLUSTER \
          --overwrite-existing

    # ==========================
    # DEPLOY BACKEND
    # ==========================
    - name: Update Backend Image
      run: |
        kubectl set image deployment/ecommerce-backend \
          backend=$ACR_LOGIN_SERVER/ecommerce-backend:$IMAGE_TAG \
          -n $NAMESPACE

    # ==========================
    # DEPLOY FRONTEND
    # ==========================
    - name: Update Frontend Image
      run: |
        kubectl set image deployment/ecommerce-frontend \
          frontend=$ACR_LOGIN_SERVER/ecommerce-frontend:$IMAGE_TAG \
          -n $NAMESPACE

    # ==========================
    # VERIFY DEPLOYMENT
    # ==========================
    - name: Verify Backend Rollout
      run: |
        kubectl rollout status deployment/ecommerce-backend \
          -n $NAMESPACE --timeout=300s

    - name: Verify Frontend Rollout
      run: |
        kubectl rollout status deployment/ecommerce-frontend \
          -n $NAMESPACE --timeout=300s

    - name: Verify Pods
      run: |
        kubectl get pods -n $NAMESPACE

    - name: Verify Services
      run: |
        kubectl get svc -n $NAMESPACE
